# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photoimage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='galleryimages/'),
            preserve_default=False,
        ),
    ]
